name: 🚀 Build and Deploy To Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0445e7a3adc243b7920930d1046778e0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a83eb7f94a5d45649363abef2a50d7b1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0445e7a3adc243b7920930d1046778e0 }}/usul-semantic-search:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'semantic-search'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7082dd6057f340dc9bcdedcfe1d8829d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0445e7a3adc243b7920930d1046778e0 }}/usul-semantic-search:${{ github.sha }}'